apiVersion: v1
kind: ConfigMap
metadata:
  name: streamify-config
  namespace: streamify
data:
  AUTH_SERVICE_URL: "http://auth-service:3001"
  VIDEO_SERVICE_URL: "http://video-service:3002"
  STREAMING_SERVICE_URL: "http://streaming-service:3003"
  BILLING_SERVICE_URL: "http://billing-service:3004"
  ANALYTICS_SERVICE_URL: "http://analytics-service:3005"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
