apiVersion: v1
kind: Secret
metadata:
  name: streamify-secrets
  namespace: streamify
type: Opaque
data:
  POSTGRES_USER: c3RyZWFtaWZ5X3VzZXI=
  POSTGRES_PASSWORD: c3RyZWFtaWZ5X3Bhc3M=
  JWT_SECRET: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
