apiVersion: v1
kind: Secret
metadata:
  name: postgres-analytics-secret
  namespace: streamify
type: Opaque
data:
  username: c3RyZWFtaWZ5X3VzZXI=
  password: c3RyZWFtaWZ5X3Bhc3M=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-billing-secret
  namespace: streamify
type: Opaque
data:
  username: c3RyZWFtaWZ5X3VzZXI=
  password: c3RyZWFtaWZ5X3Bhc3M=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-streaming-secret
  namespace: streamify
type: Opaque
data:
  username: c3RyZWFtaWZ5X3VzZXI=
  password: c3RyZWFtaWZ5X3Bhc3M=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-video-secret
  namespace: streamify
type: Opaque
data:
  username: c3RyZWFtaWZ5X3VzZXI=
  password: c3RyZWFtaWZ5X3Bhc3M=

