apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-streaming
  namespace: streamify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-streaming
  namespace: streamify
spec:
  selector:
    matchLabels:
      app: postgres-streaming
  template:
    metadata:
      labels:
        app: postgres-streaming
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres-streaming
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: streamingdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-streaming-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-streaming-secret
                  key: password
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: streaming-db-storage
      volumes:
        - name: streaming-db-storage
          persistentVolumeClaim:
            claimName: pvc-postgres-streamin
