apiVersion: v1
kind: Service
metadata:
  name: streaming-service
  namespace: streamify
spec:
  type: ClusterIP
  selector:
    app: streaming-service
  ports:
    - port: 8081
      targetPort: 8081
